using System.Formats.Tar;
using System.IO.Compression;
using System.Text;
using System.Text.Json;

namespace Oadm.Plugins.Acap;

/// <summary>An AXIS OS version range from the manifest (<c>compatibleOsVersions</c>), bounds inclusive at their own precision.</summary>
public sealed record OsVersionRange(string? Min, string? Max)
{
    public override string ToString() => (Min, Max) switch
    {
        ({ } min, { } max) => $"{min} - {max}",
        ({ } min, null) => $"{min} or later",
        (null, { } max) => $"up to {max}",
        _ => "any",
    };
}

/// <summary>
/// What an ACAP package (.eap) says about itself, read from <c>manifest.json</c> (ACAP 3/4, preferred)
/// and/or <c>package.conf</c> (legacy ACAP 2, also generated by acap-build next to the manifest).
/// </summary>
public sealed record EapManifest
{
    /// <summary>Package name (<c>appName</c> / <c>APPNAME</c>), the id used by control.cgi.</summary>
    public required string AppName { get; init; }

    public string? FriendlyName { get; init; }

    public string? Vendor { get; init; }

    public required string Version { get; init; }

    /// <summary><c>aarch64</c>, <c>armv7hf</c>, <c>mips</c>, ... or null / <c>all</c> for architecture independent packages.</summary>
    public string? Architecture { get; init; }

    public string? SchemaVersion { get; init; }

    /// <summary>manifest <c>embeddedSdkVersion</c> (schema 1.x only); informational.</summary>
    public string? EmbeddedSdkVersion { get; init; }

    /// <summary>package.conf <c>REQEMBDEVVERSION</c>, compared with <c>Properties.EmbeddedDevelopment.Version</c>.</summary>
    public string? RequiredEmbeddedDevelopmentVersion { get; init; }

    public IReadOnlyList<OsVersionRange> CompatibleOsVersions { get; init; } = [];

    /// <summary>The application asks to run as root, not allowed from AXIS OS 12.0.</summary>
    public bool RunsAsRoot { get; init; }

    public string? RunMode { get; init; }

    /// <summary>"manifest.json" or "package.conf".</summary>
    public required string Source { get; init; }

    public string DisplayName => string.IsNullOrWhiteSpace(FriendlyName) ? AppName : FriendlyName;
}

/// <summary>The file is not a usable ACAP package. Nothing was changed.</summary>
public sealed class InvalidEapException : Exception
{
    public InvalidEapException()
    {
    }

    public InvalidEapException(string message)
        : base(message)
    {
    }

    public InvalidEapException(string message, Exception innerException)
        : base(message, innerException)
    {
    }
}

/// <summary>Reads the manifest of an .eap (gzip-compressed tar) without extracting anything to disk.</summary>
public static class EapReader
{
    /// <summary>Largest manifest.json / package.conf we accept; real ones are a few KB.</summary>
    public const int MaxMetadataBytes = 1024 * 1024;

    private static readonly System.Text.RegularExpressions.Regex AppNamePattern =
        new("^[A-Za-z0-9_][A-Za-z0-9_.-]{0,63}$", System.Text.RegularExpressions.RegexOptions.CultureInvariant);

    /// <summary>True when <paramref name="name"/> is a safe ACAP package name (letters, digits, '_', '.', '-').</summary>
    public static bool IsValidAppName(string? name) => name is not null && AppNamePattern.IsMatch(name);

    public static async Task<EapManifest> ReadAsync(string path, CancellationToken ct)
    {
        var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 81920, useAsync: true);
        await using (stream.ConfigureAwait(false))
        {
            return await ReadAsync(stream, ct).ConfigureAwait(false);
        }
    }

    /// <summary>Reads the package metadata. Throws <see cref="InvalidEapException"/> for anything that is not a valid .eap.</summary>
    public static async Task<EapManifest> ReadAsync(Stream eap, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(eap);
        string? manifestJson = null;
        string? packageConf = null;
        try
        {
            var gzip = new GZipStream(eap, CompressionMode.Decompress, leaveOpen: true);
            await using (gzip.ConfigureAwait(false))
            {
                var tar = new TarReader(gzip, leaveOpen: true);
                await using (tar.ConfigureAwait(false))
                {
                    while (await tar.GetNextEntryAsync(copyData: false, ct).ConfigureAwait(false) is { } entry)
                    {
                        var name = NormalizeEntryName(entry.Name);
                        var isFile = entry.EntryType is TarEntryType.RegularFile or TarEntryType.V7RegularFile;
                        if (!isFile || entry.DataStream is null || name is not ("manifest.json" or "package.conf"))
                        {
                            continue;
                        }

                        if (entry.Length > MaxMetadataBytes)
                        {
                            throw new InvalidEapException($"{name} in the package is too large.");
                        }

                        var text = await ReadTextAsync(entry.DataStream, ct).ConfigureAwait(false);
                        if (name == "manifest.json")
                        {
                            manifestJson = text;
                        }
                        else
                        {
                            packageConf = text;
                        }

                        if (manifestJson is not null && packageConf is not null)
                        {
                            break;
                        }
                    }
                }
            }
        }
        catch (InvalidDataException ex)
        {
            throw new InvalidEapException("The file is not an ACAP package (.eap must be a gzip-compressed tar archive).", ex);
        }
        catch (FormatException ex)
        {
            throw new InvalidEapException("The file is not an ACAP package (the tar archive is damaged).", ex);
        }
        catch (EndOfStreamException ex)
        {
            throw new InvalidEapException("The file is not an ACAP package (the archive is truncated).", ex);
        }

        return Parse(manifestJson, packageConf);
    }

    /// <summary>Builds the manifest from the two metadata files; manifest.json wins, package.conf fills gaps.</summary>
    public static EapManifest Parse(string? manifestJson, string? packageConf)
    {
        if (manifestJson is null && packageConf is null)
        {
            throw new InvalidEapException("The package contains neither manifest.json nor package.conf.");
        }

        var conf = packageConf is null ? new Dictionary<string, string>() : ParsePackageConf(packageConf);
        EapManifest manifest = manifestJson is not null ? ParseManifestJson(manifestJson, conf) : FromPackageConf(conf);

        if (!IsValidAppName(manifest.AppName))
        {
            throw new InvalidEapException($"The package name \"{manifest.AppName}\" is not valid.");
        }

        if (string.IsNullOrWhiteSpace(manifest.Version))
        {
            throw new InvalidEapException("The package does not declare a version.");
        }

        return manifest;
    }

    /// <summary>Parses package.conf (shell style <c>KEY="value"</c> lines).</summary>
    public static Dictionary<string, string> ParsePackageConf(string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var raw in text.Split('\n'))
        {
            var line = raw.Trim();
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var eq = line.IndexOf('=', StringComparison.Ordinal);
            if (eq <= 0)
            {
                continue;
            }

            var value = line[(eq + 1)..].Trim();
            if (value.Length >= 2 && (value[0] == '"' || value[0] == '\'') && value[^1] == value[0])
            {
                value = value[1..^1];
            }

            result[line[..eq].Trim()] = value;
        }

        return result;
    }

    private static EapManifest ParseManifestJson(string json, Dictionary<string, string> conf)
    {
        JsonDocument doc;
        try
        {
            doc = JsonDocument.Parse(json);
        }
        catch (JsonException ex)
        {
            throw new InvalidEapException("manifest.json in the package is not valid JSON.", ex);
        }

        using (doc)
        {
            var root = doc.RootElement;
            if (root.ValueKind != JsonValueKind.Object)
            {
                throw new InvalidEapException("manifest.json in the package is not a JSON object.");
            }

            var schema = GetString(root, "schemaVersion");
            var packageConf = root.TryGetProperty("acapPackageConf", out var pc) && pc.ValueKind == JsonValueKind.Object ? pc : default;
            var setup = packageConf.ValueKind == JsonValueKind.Object && packageConf.TryGetProperty("setup", out var s) && s.ValueKind == JsonValueKind.Object ? s : default;
            if (setup.ValueKind != JsonValueKind.Object)
            {
                throw new InvalidEapException("manifest.json has no acapPackageConf.setup section.");
            }

            var ranges = ReadRanges(setup);
            if (ranges.Count == 0 && packageConf.ValueKind == JsonValueKind.Object)
            {
                ranges = ReadRanges(packageConf);
            }

            if (ranges.Count == 0)
            {
                ranges = ReadRanges(root);
            }

            var user = setup.TryGetProperty("user", out var u) && u.ValueKind == JsonValueKind.Object ? GetString(u, "username") : null;
            return new EapManifest
            {
                AppName = GetString(setup, "appName") ?? conf.GetValueOrDefault("APPNAME") ?? string.Empty,
                FriendlyName = GetString(setup, "friendlyName") ?? conf.GetValueOrDefault("APPNICENAME"),
                Vendor = GetString(setup, "vendor") ?? conf.GetValueOrDefault("VENDOR"),
                Version = GetString(setup, "version") ?? ConfVersion(conf) ?? string.Empty,
                Architecture = GetString(setup, "architecture") ?? conf.GetValueOrDefault("APPTYPE"),
                SchemaVersion = schema,
                EmbeddedSdkVersion = GetString(setup, "embeddedSdkVersion"),
                RequiredEmbeddedDevelopmentVersion = conf.GetValueOrDefault("REQEMBDEVVERSION"),
                CompatibleOsVersions = ranges,
                RunsAsRoot = string.Equals(user ?? conf.GetValueOrDefault("APPUSR"), "root", StringComparison.Ordinal),
                RunMode = GetString(setup, "runMode"),
                Source = "manifest.json",
            };
        }
    }

    private static EapManifest FromPackageConf(Dictionary<string, string> conf) => new()
    {
        AppName = conf.GetValueOrDefault("APPNAME") ?? string.Empty,
        FriendlyName = conf.GetValueOrDefault("APPNICENAME"),
        Vendor = conf.GetValueOrDefault("VENDOR"),
        Version = ConfVersion(conf) ?? string.Empty,
        Architecture = conf.GetValueOrDefault("APPTYPE"),
        RequiredEmbeddedDevelopmentVersion = conf.GetValueOrDefault("REQEMBDEVVERSION"),
        RunsAsRoot = string.Equals(conf.GetValueOrDefault("APPUSR"), "root", StringComparison.Ordinal),
        RunMode = conf.GetValueOrDefault("STARTMODE"),
        Source = "package.conf",
    };

    private static string? ConfVersion(Dictionary<string, string> conf)
    {
        if (!conf.TryGetValue("APPMAJORVERSION", out var major))
        {
            return null;
        }

        var parts = new List<string> { major };
        if (conf.TryGetValue("APPMINORVERSION", out var minor))
        {
            parts.Add(minor);
            if (conf.TryGetValue("APPMICROVERSION", out var micro))
            {
                parts.Add(micro);
            }
        }

        return string.Join('.', parts);
    }

    private static List<OsVersionRange> ReadRanges(JsonElement parent)
    {
        var list = new List<OsVersionRange>();
        if (parent.ValueKind != JsonValueKind.Object || !parent.TryGetProperty("compatibleOsVersions", out var value))
        {
            return list;
        }

        IEnumerable<JsonElement> items = value.ValueKind switch
        {
            JsonValueKind.Array => value.EnumerateArray(),
            JsonValueKind.Object => [value],
            _ => [],
        };
        foreach (var item in items.Where(i => i.ValueKind == JsonValueKind.Object))
        {
            var min = GetString(item, "min");
            var max = GetString(item, "max");
            if (min is not null || max is not null)
            {
                list.Add(new OsVersionRange(min, max));
            }
        }

        return list;
    }

    private static string? GetString(JsonElement obj, string name)
    {
        if (obj.ValueKind != JsonValueKind.Object || !obj.TryGetProperty(name, out var value))
        {
            return null;
        }

        return value.ValueKind switch
        {
            JsonValueKind.String => value.GetString(),
            JsonValueKind.Number => value.GetRawText(),
            _ => null,
        };
    }

    private static string NormalizeEntryName(string name)
    {
        var n = name.Replace('\\', '/');
        while (n.StartsWith("./", StringComparison.Ordinal))
        {
            n = n[2..];
        }

        return n.TrimStart('/');
    }

    private static async Task<string> ReadTextAsync(Stream data, CancellationToken ct)
    {
        using var buffer = new MemoryStream();
        var chunk = new byte[16384];
        int read;
        while ((read = await data.ReadAsync(chunk, ct).ConfigureAwait(false)) > 0)
        {
            if (buffer.Length + read > MaxMetadataBytes)
            {
                throw new InvalidEapException("Package metadata is too large.");
            }

            buffer.Write(chunk, 0, read);
        }

        return Encoding.UTF8.GetString(buffer.GetBuffer(), 0, (int)buffer.Length).TrimStart('﻿');
    }
}
