using System.Reflection;

using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

using Oadm.Client.Api;
using Oadm.Client.Shell;

namespace Oadm.Client.Settings;

/// <summary>
/// Where the client finds THIRD-PARTY-NOTICES.txt: next to the exe (published, installed), in the app bundle's
/// Resources folder (macOS .pkg) or, in a repository checkout, the hand-written THIRD-PARTY-NOTICES.md (the full file is
/// generated by <c>manage publish</c>).
/// </summary>
public sealed class ThirdPartyNotices(IReadOnlyList<string> candidates)
{
    public const string FileName = "THIRD-PARTY-NOTICES.txt";

    /// <summary>Largest file shown (the generated file is about 600 KB).</summary>
    public const long MaxBytes = 8 * 1024 * 1024;

    public static ThirdPartyNotices Default { get; } = new(DefaultCandidates(AppContext.BaseDirectory));

    public IReadOnlyList<string> Candidates { get; } = candidates ?? throw new ArgumentNullException(nameof(candidates));

    public static IReadOnlyList<string> DefaultCandidates(string appDirectory)
    {
        var list = new List<string>
        {
            Path.Combine(appDirectory, FileName),
            Path.GetFullPath(Path.Combine(appDirectory, "..", "Resources", FileName)), // OADM.app/Contents/MacOS -> Resources
        };
        for (var dir = new DirectoryInfo(appDirectory); dir is not null; dir = dir.Parent)
        {
            if (File.Exists(Path.Combine(dir.FullName, "Oadm.sln")))
            {
                list.Add(Path.Combine(dir.FullName, "THIRD-PARTY-NOTICES.md"));
                break;
            }
        }

        return list;
    }

    /// <summary>The first existing file, or null.</summary>
    public string? Find() => Candidates.FirstOrDefault(File.Exists);

    /// <summary>Path and text of the notices; null when no file was found.</summary>
    public async Task<(string Path, string Text)?> ReadAsync(CancellationToken ct)
    {
        if (Find() is not { } path)
        {
            return null;
        }

        if (new FileInfo(path).Length > MaxBytes)
        {
            return (path, $"{path} is larger than {MaxBytes / 1024 / 1024} MB; open it in a text editor.");
        }

        return (path, await File.ReadAllTextAsync(path, ct).ConfigureAwait(false));
    }
}

/// <summary>
/// Card "About and licenses" on the Settings page: client and server version, the OADM license and the third-party
/// notices (every bundled package with its license text) in a read-only view, loaded when first shown.
/// </summary>
public sealed partial class AboutViewModel : ObservableObject
{
    private readonly IOadmApi _api;
    private readonly ThirdPartyNotices _notices;

    public AboutViewModel(IOadmApi api, ServerConnection? connection = null, ThirdPartyNotices? notices = null)
    {
        _api = api ?? throw new ArgumentNullException(nameof(api));
        _notices = notices ?? ThirdPartyNotices.Default;
        if (connection is not null)
        {
            connection.Connected += (_, _) => _ = LoadServerVersionAsync();
        }
    }

    public const string LicenseText = "Copyright 2026 The OADM contributors. OADM is open source software under the Apache License 2.0. It contains third-party software under its own licenses, listed below.";

    /// <summary>Title of the terms of use (first line of TERMS.md).</summary>
    public string TermsTitle { get; } = Terms.Title;

    /// <summary>The terms of use without the title: shown before the license, like on the installers' license page.</summary>
    public string TermsText { get; } = Terms.Body;

    /// <summary>TERMS.md of the repository, embedded in the client.</summary>
    public static (string Title, string Body) Terms { get; } = ReadTerms();

    private static (string Title, string Body) ReadTerms()
    {
        using var stream = typeof(AboutViewModel).Assembly.GetManifestResourceStream("Oadm.Client.TERMS.md")
            ?? throw new InvalidOperationException("TERMS.md is not embedded in the client.");
        using var reader = new StreamReader(stream);
        var parts = reader.ReadToEnd().Replace("\r\n", "\n", StringComparison.Ordinal).Trim().Split('\n', 2);
        return (parts[0].Trim(), parts.Length > 1 ? parts[1].Trim() : string.Empty);
    }

    public string ClientVersion { get; } = VersionOf(typeof(AboutViewModel).Assembly);

    [ObservableProperty]
    public partial string ServerVersion { get; private set; } = "Not connected";

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(LicensesButtonText))]
    public partial bool IsShowingLicenses { get; private set; }

    /// <summary>The notices text; null until "Show licenses" was clicked (read once, kept afterwards).</summary>
    [ObservableProperty]
    public partial string? NoticesText { get; private set; }

    /// <summary>"From C:\Program Files\OADM\Client\THIRD-PARTY-NOTICES.txt" or why nothing is shown.</summary>
    [ObservableProperty]
    public partial string? NoticesSource { get; private set; }

    public string LicensesButtonText => IsShowingLicenses ? "Hide licenses" : "Show licenses";

    /// <summary>"1.2.0" from the informational version without the source revision.</summary>
    public static string VersionOf(Assembly assembly)
    {
        ArgumentNullException.ThrowIfNull(assembly);
        var version = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion
            ?? assembly.GetName().Version?.ToString() ?? "?";
        return version.Split('+')[0];
    }

    [RelayCommand]
    public async Task LoadServerVersionAsync()
    {
        try
        {
            var settings = await _api.GetSettingsAsync(CancellationToken.None).ConfigureAwait(true);
            ServerVersion = string.IsNullOrEmpty(settings.ServerVersion) ? "Unknown (older server)" : settings.ServerVersion;
        }
#pragma warning disable CA1031 // Display only: an unreachable server keeps the text.
        catch (Exception)
#pragma warning restore CA1031
        {
            ServerVersion = "Not connected";
        }
    }

    [RelayCommand]
    private async Task ToggleLicensesAsync()
    {
        if (IsShowingLicenses)
        {
            IsShowingLicenses = false;
            return;
        }

        if (NoticesText is null)
        {
            try
            {
                if (await _notices.ReadAsync(CancellationToken.None).ConfigureAwait(true) is { } notices)
                {
                    NoticesText = notices.Text;
                    NoticesSource = "From " + notices.Path;
                }
                else
                {
                    NoticesText = string.Empty;
                    NoticesSource = $"{ThirdPartyNotices.FileName} was not found.";
                }
            }
            catch (IOException ex)
            {
                NoticesText = string.Empty;
                NoticesSource = $"{ThirdPartyNotices.FileName} could not be read: {ex.Message}";
            }
            catch (UnauthorizedAccessException ex)
            {
                NoticesText = string.Empty;
                NoticesSource = $"{ThirdPartyNotices.FileName} could not be read: {ex.Message}";
            }
        }

        IsShowingLicenses = true;
    }
}
