using System.Globalization;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;

using Microsoft.Extensions.Logging;

using Oadm.Plugins.Pki.Ca;
using Oadm.Plugins.Pki.TrustStore;
using Oadm.Sdk.Network;
using Oadm.Sdk.Plugins;

namespace Oadm.Plugins.Pki;

/// <summary>Options of the PKI service (tests shorten the key and replace the clock and the trust store).</summary>
public sealed class PkiOptions
{
    /// <summary>RSA key size of generated CAs (tests use 2048 for speed).</summary>
    public int CaKeySize { get; init; } = PkiPluginInfo.CaKeySize;

    public TimeProvider Time { get; init; } = TimeProvider.System;

    /// <summary>For the default common name "OADM Root CA &lt;server name&gt;".</summary>
    public string ServerName { get; init; } = Environment.MachineName;

    /// <summary>The server's machine root store; null = the installer of the server OS.</summary>
    public ITrustStoreInstaller? TrustStore { get; init; }
}

/// <summary>
/// The PKI backend (spec <c>docs/specs/pki.md</c>, part 1): one active CA (generated by default on first start, or imported),
/// previous CAs (public parts), settings, the issued registry (read only here), trust anchors for the server's own check,
/// the server's OS trust store, export and backup. The CA key is encrypted with the server master key
/// (<see cref="ISecretProtector"/>); without a protector the plugin keeps no CA and says so.
/// </summary>
public sealed partial class PkiService : IAsyncDisposable
{
    private const string KeyPurposePrefix = "pki:ca:";

    private readonly PkiOptions _options;
    private readonly PkiStore _store;
    private readonly ISecretProtector? _secrets;
    private readonly IPluginEvents? _events;
    private readonly ITrustAnchors? _anchors;
    private readonly ILogger _logger;
    private readonly ITrustStoreInstaller _trustStore;
    private readonly SemaphoreSlim _gate = new(1, 1);
    private readonly CancellationTokenSource _stopping = new();
    private volatile CaMaterial? _ca;
    private volatile StoredCa? _stored;
    private volatile IReadOnlyList<StoredPreviousCa> _previous = [];
    private volatile PkiConfig _config = new();
    private volatile bool _generating;
    private volatile string? _generationError;
    private volatile string? _serverTrustError;
    private Task _background = Task.CompletedTask;

    public PkiService(PkiOptions options, IPluginSettings settings, ISecretProtector? secrets, IPluginEvents? events, ITrustAnchors? anchors, ILogger logger)
    {
        _options = options ?? throw new ArgumentNullException(nameof(options));
        _store = new PkiStore(settings ?? throw new ArgumentNullException(nameof(settings)));
        _secrets = secrets;
        _events = events;
        _anchors = anchors;
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _trustStore = options.TrustStore ?? TrustStoreInstallers.ForServer(logger);
    }

    /// <summary>The server offers no secret protection: no CA can be kept.</summary>
    public bool Unavailable => _secrets is null;

    /// <summary>The active CA (key null when unreadable); null while none exists.</summary>
    public CaMaterial? Ca => _ca;

    public PkiConfig Config => _config;

    /// <summary>Completes when the default CA of the first start is created (tests).</summary>
    public Task Background => _background;

    private DateTimeOffset Now => _options.Time.GetUtcNow();

    public async Task StartAsync(CancellationToken ct)
    {
        _config = await _store.LoadConfigAsync(ct).ConfigureAwait(false);
        _previous = await PrunePreviousAsync(await _store.LoadPreviousAsync(ct).ConfigureAwait(false), ct).ConfigureAwait(false);
        if (_secrets is null)
        {
            LogNoSecrets();
            return;
        }

        var stored = await _store.LoadCaAsync(ct).ConfigureAwait(false);
        if (stored is null)
        {
            _generating = true;
            _background = Task.Run(() => GenerateDefaultAsync(_stopping.Token), CancellationToken.None);
        }
        else
        {
            _stored = stored;
            _ca = LoadMaterial(stored);
            if (_ca is { HasKey: false })
            {
                LogKeyUnreadable(stored.Id);
            }
        }

        ApplyAnchors();
    }

    public async ValueTask DisposeAsync()
    {
        await _stopping.CancelAsync().ConfigureAwait(false);
        try
        {
            await _background.ConfigureAwait(false);
        }
        catch (OperationCanceledException)
        {
            // stopping
        }

        _stopping.Dispose();
        _gate.Dispose();
    }

    /// <summary>Everything the page shows; the server trust store is checked every time (cheap lookup).</summary>
    public async Task<PkiState> GetStateAsync(CancellationToken ct)
    {
        var ca = _ca;
        var stored = _stored;
        var config = _config;
        var now = Now.UtcDateTime;
        var previous = _previous.Where(p => ReadNotAfter(p.CertificatePem) is not { } end || end > now).ToList();
        var issued = await _store.LoadIssuedAsync(ct).ConfigureAwait(false);
        var counts = IssuedCounts.From(issued, ca?.Id, now, config.ExpiryWarningDays);

        bool? installed = null;
        var trustError = _serverTrustError;
        if (ca is not null)
        {
            try
            {
                installed = await _trustStore.IsInstalledAsync(ca.Certificate, ct).ConfigureAwait(false);
            }
#pragma warning disable CA1031 // A failed lookup only means "unknown" on the page.
            catch (Exception ex) when (ex is not OperationCanceledException)
#pragma warning restore CA1031
            {
                trustError ??= ex.Message;
            }
        }

        return new PkiState
        {
            Status = StatusOf(Unavailable, _generating, _generationError, ca, now, config.ExpiryWarningDays),
            Ca = ca?.Describe(stored?.Source ?? CaSource.Generated),
            KeyUnreadable = ca is { HasKey: false },
            IsGenerating = _generating,
            Unavailable = Unavailable,
            PreviousCas = [.. previous.Select(p => DescribePrevious(p, counts))],
            Config = config,
            ServerTrustInstalled = installed,
            ServerTrustError = installed == true ? null : trustError,
            IssuedDevices = counts.Devices,
            DevicesWithCurrentCa = ca is null ? 0 : counts.WithCurrentCa,
            DevicesWithPreviousCa = counts.WithPreviousCa,
            ExpiringSoon = counts.ExpiringSoon,
            RadiusCa = RadiusSummary(config.Dot1x.RadiusCaPem),
        };
    }

    /// <summary>The header status: valid until / expires in N days / expired / key unreadable.</summary>
    public static ServiceStatus StatusOf(bool unavailable, bool generating, string? generationError, CaMaterial? ca, DateTime nowUtc, int warningDays)
    {
        if (unavailable)
        {
            return new ServiceStatus(ServiceStatus.Error, "CA cannot be stored on this server", "The OADM server offers plugins no protection for secrets, so the CA key cannot be kept safe.");
        }

        if (generating)
        {
            return new ServiceStatus("accent", "Creating the certificate authority");
        }

        if (ca is null)
        {
            return generationError is null
                ? new ServiceStatus(ServiceStatus.Neutral, "No certificate authority")
                : new ServiceStatus(ServiceStatus.Error, "No certificate authority", generationError);
        }

        if (!ca.HasKey)
        {
            return new ServiceStatus(ServiceStatus.Error, "CA key cannot be read", "The CA was stored with another master key. Generate a new CA or import one.");
        }

        var notAfter = ca.Certificate.NotAfter.ToUniversalTime();
        if (nowUtc > notAfter)
        {
            return new ServiceStatus(ServiceStatus.Error, "CA expired", $"Expired on {notAfter:yyyy-MM-dd}. Generate a new CA or import one.");
        }

        var days = (int)Math.Floor((notAfter - nowUtc).TotalDays);
        if (days <= warningDays)
        {
            var text = days switch
            {
                0 => "CA expires today",
                1 => "CA expires in 1 day",
                _ => string.Create(CultureInfo.InvariantCulture, $"CA expires in {days} days"),
            };
            return new ServiceStatus(ServiceStatus.Warning, text, $"Valid until {notAfter:yyyy-MM-dd}. Generate a new CA or import one.");
        }

        return new ServiceStatus(ServiceStatus.Ok, string.Create(CultureInfo.InvariantCulture, $"CA valid until {notAfter:yyyy-MM-dd}"));
    }

    public async Task<PkiReply> GenerateAsync(GenerateRequest request, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (Unavailable)
        {
            return await ErrorAsync("The CA cannot be stored on this server.", ct).ConfigureAwait(false);
        }

        var errors = new Dictionary<string, string>(StringComparer.Ordinal);
        Add(errors, PkiFields.CommonName, PkiValidation.CommonName(request.CommonName));
        Add(errors, PkiFields.Organization, PkiValidation.Organization(request.Organization));
        Add(errors, PkiFields.ValidityYears, PkiValidation.ValidityYears(request.ValidityYears));
        if (errors.Count > 0)
        {
            return new PkiReply { Errors = errors };
        }

        if (_generating)
        {
            return await ErrorAsync("A certificate authority is being created. Try again in a moment.", ct).ConfigureAwait(false);
        }

        await _gate.WaitAsync(ct).ConfigureAwait(false);
        try
        {
            var affected = await DevicesWithCurrentCaAsync(ct).ConfigureAwait(false);
            if (_stored is not null && !request.Confirmed)
            {
                return new PkiReply { NeedsConfirmation = true, DevicesWithCurrentCa = affected };
            }

            _generating = true;
            await PublishAsync().ConfigureAwait(false);
            CaMaterial material;
            try
            {
                var now = Now;
                material = await Task.Run(() => CaGenerator.Generate(request.CommonName!, request.Organization, request.ValidityYears, now, _options.CaKeySize), ct).ConfigureAwait(false);
            }
            finally
            {
                _generating = false;
            }

            await ReplaceAsync(material, CaSource.Generated, ct).ConfigureAwait(false);
            var (subject, notAfter) = (material.Certificate.Subject, material.Certificate.NotAfter);
            LogGenerated(subject, notAfter);
        }
        finally
        {
            _gate.Release();
        }

        await PublishAsync().ConfigureAwait(false);
        return new PkiReply { Ok = true, State = await GetStateAsync(ct).ConfigureAwait(false) };
    }

    public async Task<PkiReply> ImportAsync(ImportRequest request, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (Unavailable)
        {
            return await ErrorAsync("The CA cannot be stored on this server.", ct).ConfigureAwait(false);
        }

        if (!TryDecode(request.FileBase64, out var file) || file.Length == 0)
        {
            return new PkiReply { Errors = One(PkiFields.File, file is { Length: 0 } && request.FileBase64 is { Length: > 0 } ? "The file cannot be read." : "Choose a file.") };
        }

        byte[]? keyFile = null;
        if (!string.IsNullOrEmpty(request.KeyFileBase64) && !TryDecode(request.KeyFileBase64, out keyFile))
        {
            return new PkiReply { Errors = One(PkiFields.KeyFile, "The key file cannot be read.") };
        }

        var result = CaImporter.Import(new CaImportInput(file, request.FileName, request.Password, keyFile, request.KeyPassword), Now, _config.DeviceCertValidityDays);
        if (result.Ca is not { } material)
        {
            return new PkiReply { Errors = result.Errors };
        }

        await _gate.WaitAsync(ct).ConfigureAwait(false);
        try
        {
            var affected = await DevicesWithCurrentCaAsync(ct).ConfigureAwait(false);
            if (_stored is not null && _stored.Id != material.Id && !request.Confirmed)
            {
                material.Dispose();
                return new PkiReply { NeedsConfirmation = true, DevicesWithCurrentCa = affected };
            }

            await ReplaceAsync(material, CaSource.Imported, ct).ConfigureAwait(false);
            LogImported(material.Certificate.Subject, material.Chain.Count);
        }
        finally
        {
            _gate.Release();
        }

        await PublishAsync().ConfigureAwait(false);
        return new PkiReply { Ok = true, State = await GetStateAsync(ct).ConfigureAwait(false) };
    }

    /// <summary>Devices whose newest certificate comes from the current CA (the replace warning).</summary>
    public async Task<PreviewReplaceReply> PreviewReplaceAsync(CancellationToken ct) =>
        new(await DevicesWithCurrentCaAsync(ct).ConfigureAwait(false));

    public FileReply ExportPublic(ExportRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        var ca = _ca;
        if (ca is null)
        {
            return new FileReply { Error = "There is no certificate authority yet." };
        }

        return Export(ca.Certificate, ca.Chain, request.Format);
    }

    public FileReply ExportPrevious(ExportPreviousRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        var previous = _previous.FirstOrDefault(p => string.Equals(p.Id, request.Id, StringComparison.OrdinalIgnoreCase));
        if (previous is null)
        {
            return new FileReply { Error = "This previous CA no longer exists." };
        }

        var certificates = CaCertificates.ReadPemCertificates(previous.CertificatePem);
        var chain = previous.ChainPem.SelectMany(CaCertificates.ReadPemCertificates).ToList();
        try
        {
            return certificates.Count == 0 ? new FileReply { Error = "The certificate cannot be read." } : Export(certificates[0], chain, request.Format);
        }
        finally
        {
            foreach (var certificate in certificates.Concat(chain))
            {
                certificate.Dispose();
            }
        }
    }

    public async Task<PkiReply> RemovePreviousAsync(RemovePreviousRequest request, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(request);
        await _gate.WaitAsync(ct).ConfigureAwait(false);
        try
        {
            var list = _previous.Where(p => !string.Equals(p.Id, request.Id, StringComparison.OrdinalIgnoreCase)).ToList();
            if (list.Count == _previous.Count)
            {
                return await ErrorAsync("This previous CA no longer exists.", ct).ConfigureAwait(false);
            }

            await _store.SavePreviousAsync(list, ct).ConfigureAwait(false);
            _previous = list;
            ApplyAnchors();
            LogPreviousRemoved(request.Id ?? string.Empty);
        }
        finally
        {
            _gate.Release();
        }

        await PublishAsync().ConfigureAwait(false);
        return new PkiReply { Ok = true, State = await GetStateAsync(ct).ConfigureAwait(false) };
    }

    /// <summary>PKCS#12 with certificate, chain and key, AES-256-CBC + SHA-256, 100,000 iterations. The password is never stored or logged.</summary>
    public FileReply Backup(BackupRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (PkiValidation.BackupPassword(request.Password) is { } passwordError)
        {
            return new FileReply { Errors = One(PkiFields.Password, passwordError) };
        }

        var ca = _ca;
        if (ca is not { HasKey: true })
        {
            return new FileReply { Error = ca is null ? "There is no certificate authority yet." : "The CA key cannot be read, so it cannot be backed up." };
        }

        using var withKey = ca.WithPrivateKey();
        var collection = new X509Certificate2Collection { withKey };
        foreach (var certificate in ca.Chain)
        {
            collection.Add(certificate);
        }

        var bytes = collection.ExportPkcs12(new PbeParameters(PbeEncryptionAlgorithm.Aes256Cbc, HashAlgorithmName.SHA256, 100_000), request.Password);
        LogBackup(ca.Certificate.Subject);
        return new FileReply { FileName = CaCertificates.FileNameFor(CaCertificates.CommonName(ca.Certificate), ".pfx"), DataBase64 = Convert.ToBase64String(bytes) };
    }

    /// <summary>Installs the active CA into the server's machine root store.</summary>
    public async Task<InstallReply> InstallServerTrustAsync(CancellationToken ct)
    {
        var ca = _ca;
        if (ca is null)
        {
            return new InstallReply(false, "There is no certificate authority yet.", await GetStateAsync(ct).ConfigureAwait(false));
        }

        TrustStoreResult result;
        try
        {
            result = await _trustStore.InstallAsync(ca.Certificate, ct).ConfigureAwait(false);
        }
#pragma warning disable CA1031 // Shown on the page.
        catch (Exception ex) when (ex is not OperationCanceledException)
#pragma warning restore CA1031
        {
            result = new TrustStoreResult(false, ex.Message);
        }

        _serverTrustError = result.Error;
        if (result.Installed)
        {
            LogTrustInstalled(ca.Certificate.Subject);
        }
        else
        {
            LogTrustFailed(ca.Certificate.Subject, result.Error ?? string.Empty);
        }

        await PublishAsync().ConfigureAwait(false);
        return new InstallReply(result.Installed, result.Error, await GetStateAsync(ct).ConfigureAwait(false));
    }

    public async Task<PkiReply> SaveSettingsAsync(SaveSettingsRequest request, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (request.Config is not { } config)
        {
            return await ErrorAsync("The settings are missing.", ct).ConfigureAwait(false);
        }

        var dot1x = config.Dot1x ?? new Dot1xConfig();
        config = config with
        {
            Dot1x = dot1x with
            {
                CustomIdentity = dot1x.CustomIdentity?.Trim() ?? string.Empty,
                RadiusCaPem = dot1x.RadiusCa == RadiusCaSource.Imported ? dot1x.RadiusCaPem : null,
            },
        };
        var errors = PkiValidation.Config(config);
        if (!errors.ContainsKey(PkiFields.RadiusCa) && config.Dot1x.RadiusCaPem is { } pem && RadiusSummary(pem) is null)
        {
            errors[PkiFields.RadiusCa] = "The CA certificate of the RADIUS server cannot be read. Import it again.";
        }

        if (errors.Count > 0)
        {
            return new PkiReply { Errors = errors };
        }

        await _store.SaveConfigAsync(config, ct).ConfigureAwait(false);
        _config = config;
        LogSettingsSaved();
        await PublishAsync().ConfigureAwait(false);
        return new PkiReply { Ok = true, State = await GetStateAsync(ct).ConfigureAwait(false) };
    }

    /// <summary>Checks a RADIUS server CA file (PEM or DER, public only); Save stores it with the settings.</summary>
    public static RadiusCaReply ImportRadiusCa(ImportRadiusCaRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (!TryDecode(request.FileBase64, out var bytes) || bytes.Length == 0)
        {
            return new RadiusCaReply { Errors = One(PkiFields.RadiusCa, "The file cannot be read.") };
        }

        if (bytes.Length > PkiPluginInfo.MaxImportBytes)
        {
            return new RadiusCaReply { Errors = One(PkiFields.RadiusCa, "The file is larger than 1 MB.") };
        }

        X509Certificate2? certificate;
        try
        {
            certificate = CaCertificates.ReadSingleCertificate(bytes);
        }
        catch (Exception ex) when (ex is CryptographicException or FormatException)
        {
            certificate = null;
        }

        if (certificate is null)
        {
            return new RadiusCaReply { Errors = One(PkiFields.RadiusCa, "The file is not a certificate (.crt or .cer, PEM or DER).") };
        }

        using (certificate)
        {
            var basic = certificate.Extensions.OfType<X509BasicConstraintsExtension>().FirstOrDefault();
            if (basic is { CertificateAuthority: false })
            {
                return new RadiusCaReply { Errors = One(PkiFields.RadiusCa, "This is not a CA certificate. Choose the CA that issued the RADIUS server's certificate.") };
            }

            return new RadiusCaReply { Pem = CaCertificates.ToPem(certificate), Summary = CaCertificates.Summarize(certificate) };
        }
    }

    /// <summary>
    /// Device certificate validity for a certificate issued now: the setting, shortened to the CA's end of validity (logged).
    /// Used by the issuing task plugins.
    /// </summary>
    public TimeSpan DeviceCertificateValidity()
    {
        var wanted = TimeSpan.FromDays(_config.DeviceCertValidityDays);
        if (_ca is not { } ca)
        {
            return wanted;
        }

        var left = ca.Certificate.NotAfter.ToUniversalTime() - Now.UtcDateTime;
        if (left < wanted)
        {
            var leftDays = Math.Max(0, (int)left.TotalDays);
            LogValidityShortened(_config.DeviceCertValidityDays, leftDays);
            return left < TimeSpan.Zero ? TimeSpan.Zero : left;
        }

        return wanted;
    }

    private async Task GenerateDefaultAsync(CancellationToken ct)
    {
        try
        {
            await _gate.WaitAsync(ct).ConfigureAwait(false);
            try
            {
                if (_stored is not null)
                {
                    return;
                }

                var name = PkiPluginInfo.DefaultCommonName(_options.ServerName);
                var material = CaGenerator.Generate(name, null, PkiPluginInfo.DefaultValidityYears, Now, _options.CaKeySize);
                await ReplaceAsync(material, CaSource.Generated, ct).ConfigureAwait(false);
                var (subject, notAfter) = (material.Certificate.Subject, material.Certificate.NotAfter);
                LogDefaultGenerated(subject, notAfter);
            }
            finally
            {
                _generating = false;
                _gate.Release();
            }
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested)
        {
            _generating = false;
            return;
        }
#pragma warning disable CA1031 // Shown in the status line; the user can generate or import.
        catch (Exception ex)
#pragma warning restore CA1031
        {
            _generationError = "Creating the CA failed: " + ex.Message;
            LogGenerationFailed(ex);
        }

        await PublishAsync().ConfigureAwait(false);
    }

    /// <summary>The new CA becomes active; the current one moves to the previous CAs (public part). Call inside the gate.</summary>
    private async Task ReplaceAsync(CaMaterial material, string source, CancellationToken ct)
    {
        var now = Now.UtcDateTime;
        var previous = _previous.ToList();
        if (_stored is { } current && !string.Equals(current.Id, material.Id, StringComparison.OrdinalIgnoreCase))
        {
            previous.Insert(0, new StoredPreviousCa { Id = current.Id, CertificatePem = current.CertificatePem, ChainPem = current.ChainPem, ReplacedUtc = now });
        }

        previous = [.. previous
            .Where(p => !string.Equals(p.Id, material.Id, StringComparison.OrdinalIgnoreCase))
            .DistinctBy(p => p.Id, StringComparer.OrdinalIgnoreCase)
            .Take(PkiPluginInfo.MaxPreviousCas)];

        var stored = new StoredCa
        {
            Id = material.Id,
            Source = source,
            CertificatePem = material.CertificatePem,
            ChainPem = material.ChainPem,
            KeyProtected = _secrets!.Protect(material.KeyPkcs8Pem!, KeyPurposePrefix + material.Id),
            CreatedUtc = now,
        };
        await _store.SavePreviousAsync(previous, ct).ConfigureAwait(false);
        await _store.SaveCaAsync(stored, ct).ConfigureAwait(false);
        _previous = previous;
        _stored = stored;
        _ca = material; // the replaced material is left to the GC: a concurrent state read may still use it
        _generationError = null;
        _serverTrustError = null;
        ApplyAnchors();
    }

    private CaMaterial? LoadMaterial(StoredCa stored)
    {
        List<X509Certificate2> certificates;
        try
        {
            certificates = CaCertificates.ReadPemCertificates(stored.CertificatePem);
        }
        catch (Exception ex) when (ex is CryptographicException or FormatException)
        {
            certificates = [];
        }

        if (certificates.Count == 0)
        {
            LogStoredCaUnreadable(stored.Id);
            return null;
        }

        var chain = new List<X509Certificate2>();
        foreach (var pem in stored.ChainPem)
        {
            try
            {
                chain.AddRange(CaCertificates.ReadPemCertificates(pem));
            }
            catch (Exception ex) when (ex is CryptographicException or FormatException)
            {
                // a damaged chain entry is left out
            }
        }

        string? key;
        try
        {
            key = _secrets!.Unprotect(stored.KeyProtected, KeyPurposePrefix + stored.Id);
        }
        catch (Exception ex) when (ex is CryptographicException or FormatException or ArgumentException)
        {
            key = null;
        }

        return new CaMaterial(certificates[0], chain, key);
    }

    /// <summary>The active CA with its chain and the previous CAs with theirs (public parts) for the server's own check.</summary>
    private void ApplyAnchors()
    {
        if (_anchors is null)
        {
            return;
        }

        var der = new List<byte[]>();
        if (_ca is { } ca)
        {
            der.Add(ca.Certificate.RawData);
            der.AddRange(ca.Chain.Select(c => c.RawData));
        }

        foreach (var previous in _previous)
        {
            foreach (var pem in previous.ChainPem.Prepend(previous.CertificatePem))
            {
                try
                {
                    foreach (var certificate in CaCertificates.ReadPemCertificates(pem))
                    {
                        using (certificate)
                        {
                            der.Add(certificate.RawData);
                        }
                    }
                }
                catch (Exception ex) when (ex is CryptographicException or FormatException)
                {
                    // unreadable entries are not trusted
                }
            }
        }

        _anchors.Set(der);
    }

    private async Task<IReadOnlyList<StoredPreviousCa>> PrunePreviousAsync(List<StoredPreviousCa> previous, CancellationToken ct)
    {
        var now = Now.UtcDateTime;
        var kept = previous.Where(p => ReadNotAfter(p.CertificatePem) is not { } end || end > now).ToList();
        if (kept.Count != previous.Count)
        {
            await _store.SavePreviousAsync(kept, ct).ConfigureAwait(false);
            LogPreviousExpired(previous.Count - kept.Count);
        }

        return kept;
    }

    private async Task<int> DevicesWithCurrentCaAsync(CancellationToken ct)
    {
        if (_ca is not { } ca)
        {
            return 0;
        }

        var issued = await _store.LoadIssuedAsync(ct).ConfigureAwait(false);
        return IssuedCounts.From(issued, ca.Id, Now.UtcDateTime, _config.ExpiryWarningDays).WithCurrentCa;
    }

    private async Task PublishAsync()
    {
        if (_events is null)
        {
            return;
        }

        try
        {
            _events.Publish(PkiMethods.StateTopic, PkiJson.Serialize(await GetStateAsync(CancellationToken.None).ConfigureAwait(false)));
        }
#pragma warning disable CA1031 // Events are best effort; pages re-read the state.
        catch (Exception ex)
#pragma warning restore CA1031
        {
            LogPublishFailed(ex);
        }
    }

    private async Task<PkiReply> ErrorAsync(string message, CancellationToken ct) =>
        new() { Error = message, State = await GetStateAsync(ct).ConfigureAwait(false) };

    private static FileReply Export(X509Certificate2 certificate, IReadOnlyList<X509Certificate2> chain, string? format)
    {
        var name = CaCertificates.CommonName(certificate);
        switch (format?.ToLowerInvariant())
        {
            case "pem":
                var pem = new StringBuilder(CaCertificates.ToPem(certificate));
                foreach (var issuer in chain)
                {
                    pem.Append(CaCertificates.ToPem(issuer));
                }

                return new FileReply { FileName = CaCertificates.FileNameFor(name, ".crt"), DataBase64 = Convert.ToBase64String(Encoding.ASCII.GetBytes(pem.ToString())) };
            case "der":
                return new FileReply { FileName = CaCertificates.FileNameFor(name, ".cer"), DataBase64 = Convert.ToBase64String(certificate.RawData) };
            default:
                return new FileReply { Error = "Choose PEM (.crt) or DER (.cer)." };
        }
    }

    private static PreviousCaInfo DescribePrevious(StoredPreviousCa previous, IssuedCounts counts)
    {
        var info = new PreviousCaInfo { Id = previous.Id, ReplacedUtc = previous.ReplacedUtc, Devices = counts.DevicesPerCa.GetValueOrDefault(previous.Id) };
        try
        {
            var certificates = CaCertificates.ReadPemCertificates(previous.CertificatePem);
            if (certificates.Count > 0)
            {
                using var certificate = certificates[0];
                info = info with
                {
                    CommonName = CaCertificates.CommonName(certificate),
                    Subject = certificate.Subject,
                    NotAfterUtc = certificate.NotAfter.ToUniversalTime(),
                };
            }
        }
        catch (Exception ex) when (ex is CryptographicException or FormatException)
        {
            info = info with { CommonName = previous.Id };
        }

        return info;
    }

    private static DateTime? ReadNotAfter(string pem)
    {
        try
        {
            var certificates = CaCertificates.ReadPemCertificates(pem);
            if (certificates.Count == 0)
            {
                return null;
            }

            using var certificate = certificates[0];
            return certificate.NotAfter.ToUniversalTime();
        }
        catch (Exception ex) when (ex is CryptographicException or FormatException)
        {
            return null;
        }
    }

    private static CertificateSummary? RadiusSummary(string? pem)
    {
        if (string.IsNullOrWhiteSpace(pem))
        {
            return null;
        }

        try
        {
            var certificates = CaCertificates.ReadPemCertificates(pem);
            if (certificates.Count == 0)
            {
                return null;
            }

            using var certificate = certificates[0];
            return CaCertificates.Summarize(certificate);
        }
        catch (Exception ex) when (ex is CryptographicException or FormatException)
        {
            return null;
        }
    }

    private static bool TryDecode(string? base64, out byte[] bytes)
    {
        bytes = [];
        if (string.IsNullOrEmpty(base64))
        {
            return false;
        }

        try
        {
            bytes = Convert.FromBase64String(base64);
            return true;
        }
        catch (FormatException)
        {
            return false;
        }
    }

    private static Dictionary<string, string> One(string field, string message) => new(StringComparer.Ordinal) { [field] = message };

    private static void Add(Dictionary<string, string> errors, string field, string? message)
    {
        if (message is not null)
        {
            errors[field] = message;
        }
    }

    [LoggerMessage(Level = LogLevel.Warning, Message = "PKI: the server offers no secret protection; no CA is kept")]
    private partial void LogNoSecrets();

    [LoggerMessage(Level = LogLevel.Error, Message = "PKI: the key of the stored CA {Id} cannot be decrypted (other master key); generate or import a CA")]
    private partial void LogKeyUnreadable(string id);

    [LoggerMessage(Level = LogLevel.Error, Message = "PKI: the stored CA {Id} cannot be read")]
    private partial void LogStoredCaUnreadable(string id);

    [LoggerMessage(Level = LogLevel.Information, Message = "PKI: generated the default CA {Subject}, valid until {NotAfter:yyyy-MM-dd}")]
    private partial void LogDefaultGenerated(string subject, DateTime notAfter);

    [LoggerMessage(Level = LogLevel.Information, Message = "PKI: generated a new CA {Subject}, valid until {NotAfter:yyyy-MM-dd}; the previous CA was kept for the transition")]
    private partial void LogGenerated(string subject, DateTime notAfter);

    [LoggerMessage(Level = LogLevel.Information, Message = "PKI: imported the CA {Subject} with {ChainCount} issuer certificates; the previous CA was kept for the transition")]
    private partial void LogImported(string subject, int chainCount);

    [LoggerMessage(Level = LogLevel.Error, Message = "PKI: creating the default CA failed")]
    private partial void LogGenerationFailed(Exception ex);

    [LoggerMessage(Level = LogLevel.Information, Message = "PKI: removed the previous CA {Id}")]
    private partial void LogPreviousRemoved(string id);

    [LoggerMessage(Level = LogLevel.Information, Message = "PKI: removed {Count} expired previous CAs")]
    private partial void LogPreviousExpired(int count);

    [LoggerMessage(Level = LogLevel.Information, Message = "PKI: CA backup exported ({Subject})")]
    private partial void LogBackup(string subject);

    [LoggerMessage(Level = LogLevel.Information, Message = "PKI: installed the CA {Subject} into the server's trusted root store")]
    private partial void LogTrustInstalled(string subject);

    [LoggerMessage(Level = LogLevel.Warning, Message = "PKI: installing the CA {Subject} into the server's trusted root store failed: {Error}")]
    private partial void LogTrustFailed(string subject, string error);

    [LoggerMessage(Level = LogLevel.Information, Message = "PKI: settings saved")]
    private partial void LogSettingsSaved();

    [LoggerMessage(Level = LogLevel.Information, Message = "PKI: device certificate validity shortened from {Days} to {Left} days (end of the CA)")]
    private partial void LogValidityShortened(int days, int left);

    [LoggerMessage(Level = LogLevel.Warning, Message = "PKI: publishing the state failed")]
    private partial void LogPublishFailed(Exception ex);
}
