<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- generated code is not linted -->
    <NoWarn>$(NoWarn);CS1591;CA1716;CA1707;CA1711;CA1822</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.*" />
    <PackageReference Include="Grpc.Net.Client" Version="2.*" />
    <PackageReference Include="Grpc.AspNetCore.Server" Version="2.*" />
    <PackageReference Include="Grpc.Tools" Version="2.*" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="Protos\*.proto" GrpcServices="Both" ProtoRoot="." />
  </ItemGroup>
</Project>
